- name: installing cart component
  hosts: cart
  become: yes
  tasks: 
  - name: disable module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: creating the app cart
    ansible.builtin.file:
      path: /app
      state: directory

  - name: adding roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: downloading cart file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: extracting the cart file
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    community.general.npm:
      path: /app

  - name: adding system services
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
    
  - name: system daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: starting the services
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes