- name: installing mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: replacing the repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
  - name: starting the service
    ansible.builtin.service:
      name: mongodb-org
      state: started
      enabled: yes
    
  - name: replacing the localhost
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

