- name: installing redis
  hosts: redis
  become: yes
  tasks: 
  - name: disable module
    ansible.builtin.command: dnf module disable redis -y

  - name: enable module
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present
    
  - name: allowing remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: starting services
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes