- name: installing user component
  hosts: user
  become: yes
  tasks: 
  - name: disable module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: creating the app user
    ansible.builtin.file:
      path: /app
      state: directory

  - name: adding roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: downloading user file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: extracting the user file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    community.general.npm:
      path: /app

  - name: adding system services
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
    
  - name: system daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: starting the services
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes